---
openstack_infra_heat_stack:     "{{ opt_infra_heat_stack  | default('files/heat_stack.yaml') }}"
openstack_network_prefix:       "{{ opt_network_prefix    | default('openshift-ansible-'+cluster_id) }}"
openstack_network_cidr:         "{{ opt_net_cidr          | default('192.168.' + ( ( 1048576 | random % 256 ) | string() ) + '.0/24') }}"
openstack_network_external_net: "{{ opt_external_net      | default('external') }}"
openstack_floating_ip_pools:    "{{ opt_floating_ip_pools | default('external')        | oo_split() }}"
openstack_network_dns:          "{{ opt_dns               | default('8.8.8.8,8.8.4.4') | oo_split() }}"
openstack_ssh_keypair:          "{{ opt_keypair           | default(lookup('env', 'LOGNAME')+'_key') }}"
openstack_ssh_public_key:       "{{ lookup('file', opt_public_key | default('~/.ssh/id_rsa.pub')) }}"
openstack_ssh_access_from:      "{{ opt_ssh_from          | default('0.0.0.0/0') }}"
openstack_flavor:
  master: "{{ opt_master_flavor | default('m1.small') }}"
  node:   "{{ opt_node_flavor   | default('m1.medium') }}"

deployment_vars:
  origin:
    image: "{{ opt_image | default('centos-70-raw') }}"
    ssh_user: openshift
    sudo: yes
  online:
    image:
    ssh_user: root
    sudo: no
  enterprise:
    image: "{{ opt_image | default('rhel-guest-image-7.1-20150224.0.x86_64') }}"
    ssh_user: openshift
    sudo: yes
